openapi: 3.1.0
info:
  description: |
    ## Overview
    An API specification to perform custom testing and validation of Knak Asset content.

    By implementing a service conforming to this API specification, you will be able to initiate a content test from the Knak UI, and results from your service will be displayed to the Knak User. For information on how to configure the connection to your custom validator in Knak, see our guide [here](https://help.knak.io/en/articles/8708391-setting-up-a-custom-validator-integration).

    ## Authentication
    As part of the Integration Configuration stage in Knak, you are able to specify your own HTTP security header name and value. These values are referred to by `<security-header-name>` and `<security-header-value>` in this specification, and will be present in every request.
  version: V1
  title: Knak Custom Validator API Reference — Status
  x-logo:
    url: https://s3.amazonaws.com/assets.knak.io/img/Knak-Logo-Medium.png
servers:
- url: https://yourService.com/yourValidationApi
- url: https://example.com
tags:
- name: Status
paths:
  /v1/ping:
    get:
      tags:
      - Status
      summary: Status check
      description: Check to see that the service is responsive, indicating to the User that the service
        is available. Any 200 response will be considered a success.
      security:
      - customSecurityHeader: []
      responses:
        200:
          description: ''
